### ISSUE TITLE
FTToolsLauncher may crash if almTimeout is set to 0 when running ALM tests

### ISSUE THREAD

**Issue by soleverxu** [MicroFocus/ADM-FT-ToolsLauncher#70]
**Tool**
FTToolsLauncher `1.0.23.2025` (`v1.0 beta rev7`)

**Describe the bug**
The FTToolsLauncher tool may crash if `almTimeout` is set to 0 when running ALM tests.
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: Current test set is null.
   at HpToolsLauncher.AlmTestSetsRunner.SetTestResults(ITSTest& currentTest, IExecutionStatus executionStatus, ITestSet targetTestSet, TestRunResults activeTestDesc, TestSuiteRunResults runDesc, String testPath, String abortFilename)
   at HpToolsLauncher.AlmTestSetsRunner.RunTestSet(String tsFolderName, String tsName, String testParameters, Double timeout, QcRunMode runMode, String runHost, Boolean isFilterSelected, String filterByName, List`1 filterByStatuses, TestStorageType testStorageType)
   at HpToolsLauncher.AlmTestSetsRunner.Run()
   at HpToolsLauncher.Launcher.Run()
   at HpToolsLauncher.Program.Main(String[] args)
```

**To Reproduce**
1. Create a parameter file with ALM test settings, set `almTimeout` to zero (`0`).
2. Run FTToolsLauncher with the above parameter file.
3. FTToolsLauncher tool may crash.

**Expected behavior**
If timeout is set to zero or a very small amount of seconds, the FTToolsLauncher shall not crash and a meaningful message shall be printed. The test itself shall be started and run normally, and the **timeout error** can be printed.

**OS and testing tools (please complete the following information):**
 - OS: Windows 10
 - UFT One version: 2021
 - ALM version: 16.0

**Comment by soleverxu** [comment]
Fixed in [v1.0 beta (rev.9)](https://github.com/MicroFocus/ADM-FT-ToolsLauncher/releases/tag/v1.0-beta-rev9), FTToolsLauncher **v1.0.29.221**.
